AUTO_SHIFT_ENABLE = yes
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
COMMAND_ENABLE = yes // disable for BOTH_SHIFTS_TURNS_ON_CAPS_WORD
CONSOLE_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
VIA_ENABLE = yes
VIAL_ENABLE = yes
